module VanishingSorou

export RootUnity, Sorou, TermBag,
    primitive_root, root_order,
    weight, sorou_order, relative_order, height,
    rotate, normalize_by_first,
    sorou_key, canonical_rotation,
    numerical_value,
    prime_factors_distinct, top_prime,
    decompose_by_top_prime, subsidiary_weights, recompose_from_bags,
    ExactValueSig, EVInt, EVNode,
    exact_value, is_vanishing_exact,
    subsidiary_values,
    proper_nonempty_subbags,
    is_minimal_vanishing_prop23,
    VanishingType, RType, SumType, RecursiveType,
    type_weight, representative_sorou,
    contains_terms, remove_terms,
    ordered_nonempty_term_partitions,
    representative_sorou_containing,
    subtype_changes_f0,
    TypeCatalog, add_type!, types_of_weight, all_types, max_type_weight,
    tiny_seed_catalog,
    positive_nondecreasing_partitions,
    type_uses_only_primes_less_than,
    gen_next_types_f0_one,
    extend_catalog_next_f0_one!,
    generate_until_f0_one!,
    lower_prime_product, roots_with_order_dividing,
    candidate_f0s_naive,
    gen_next_types_with_f0_candidates,
    extend_catalog_next_with_f0_candidates!,
    direct_sum_types_of_weight,
    vanishing_type_choices_for_weight,
    generate_until_with_f0_candidates!,
    type_strings,
    catalog_types_of_weight,
    catalog_type_strings_of_weight,
    catalog_summary,
    print_catalog_summary,
    print_catalog_by_weight,
    canonical_sorou_key,
    representative_key,
    group_types_by_representative,
    duplicate_representative_groups,
    unique_types_by_representative,
    print_duplicate_representative_groups,
    catalog_unique_type_count_by_representative,
    catalog_diagnostic_summary,
    print_catalog_diagnostic_summary,
    print_catalog_duplicates_by_weight,
    write_catalog_by_weight,
    expected_counts_to_16_expanded,
    catalog_count_dict,
    catalog_unique_count_dict,
    compare_catalog_counts_to_16,
    print_compare_catalog_counts_to_16,
    catalog_matches_counts_to_16,
    order_parity,
    unordered_order_parity,
    representative_height,
    representative_order_parity,
    representative_unordered_order_parity,
    representative_invariants,
    catalog_representative_invariant_rows,
    print_catalog_representative_invariants,
    write_catalog_representative_invariants,
    gen_sorou,
    gen_sorou_containing,
    gen_nonminimal_sorou_containing,
    rotations_containing,
    subsidiary_from_subtype_containing_f0,
    type_height_set,
    type_order_parity_set,
    type_unordered_order_parity_set,
    type_full_invariant_summary,
    print_type_full_invariant_summary,
    catalog_full_invariant_rows,
    max_height_by_weight,
    height_distribution_by_weight,
    rows_with_height_at_least,
    print_full_invariant_summary_by_weight,
    write_catalog_full_invariants,
    print_full_invariant_rows_summary,
    filter_rows_with_height_at_least,
    write_full_invariant_rows,
    canonical_slot_assignments_for_subtypes,
    consecutive_equal_subtype_ranges,
    choose_k_from_available,
    distinct_slot_tuples,
    containing_key,
    gen_sorou_with_memo_stats,
    completed_type_strings_from_incremental_file,
    write_full_invariants_one_weight_incremental,
    paper_type_string,
    catalog_paper_type_strings_of_weight,
    write_catalog_paper_type_strings,
    example_R3, example_R5_R3, example_R5_R3_slot_form

include("core.jl")
include("decompose.jl")
include("exact_value.jl")
include("prop23.jl")
include("types.jl")
include("invariants.jl")
include("algorithm1_types.jl")
include("algorithm2_sorou.jl")
include("examples.jl")

end