import { Checklist } from "./checklistSchema";

export const MOCK_CHECKLISTS: Checklist[] = [
  {
    id: "cl-mock-1",
    routeId: "SO-8-04-0",
    date: "2025-03-15",
    observer: "Ana K.",
    completionPercentage: 100,
    requiredComplete: true,
    items: [
      { id: "front", label: "Front view", category: "structure", required: true, status: "captured", visibility: "good", photoPlaceholder: "IMG_2041_front_reef.jpg", note: "Clear visibility, full structure visible" },
      { id: "back", label: "Back view", category: "structure", required: true, status: "captured", visibility: "good", photoPlaceholder: "IMG_2042_back_reef.jpg" },
      { id: "top", label: "Top / summit view", category: "structure", required: true, status: "captured", visibility: "good", photoPlaceholder: "IMG_2043_top_reef.jpg", note: "Dense algae coverage on summit" },
      { id: "left", label: "Left side", category: "structure", required: false, status: "captured", visibility: "good", photoPlaceholder: "IMG_2044_left_reef.jpg" },
      { id: "right", label: "Right side", category: "structure", required: false, status: "captured", visibility: "medium", photoPlaceholder: "IMG_2045_right_reef.jpg", note: "Slight particulates on this side" },
      { id: "lower", label: "Lower side / shaded side", category: "structure", required: false, status: "captured", visibility: "medium", photoPlaceholder: "IMG_2046_lower_reef.jpg", disturbanceRisk: "low", note: "Some sediment disturbed by current" },
      { id: "gp1", label: "Growth plate 1", category: "growth_plate", required: true, status: "captured", visibility: "good", photoPlaceholder: "IMG_2047_gp1.jpg", note: "Moderate bryozoan coverage" },
      { id: "gp2", label: "Growth plate 2", category: "growth_plate", required: true, status: "captured", visibility: "good", photoPlaceholder: "IMG_2048_gp2.jpg", note: "Polychaete tubes establishing" },
      { id: "gp3", label: "Growth plate 3", category: "growth_plate", required: false, status: "captured", visibility: "good", photoPlaceholder: "IMG_2049_gp3.jpg" },
      { id: "gp4", label: "Growth plate 4", category: "growth_plate", required: false, status: "captured", visibility: "medium", photoPlaceholder: "IMG_2050_gp4.jpg", note: "Sparse growth, mostly bare" },
      { id: "gp5", label: "Growth plate 5", category: "growth_plate", required: false, status: "captured", visibility: "good", photoPlaceholder: "IMG_2051_gp5.jpg" },
      { id: "seabed", label: "Surrounding seabed", category: "context", required: false, status: "captured", visibility: "good", photoPlaceholder: "IMG_2052_seabed.jpg", note: "Sandy bottom, some posidonia patches" },
      { id: "wide", label: "Wide context shot", category: "context", required: false, status: "captured", visibility: "good", photoPlaceholder: "IMG_2053_wide_context.jpg" },
      { id: "waste", label: "Any visible waste/damage", category: "issue", required: false, status: "skipped", note: "No waste observed" },
      { id: "unusual", label: "Any unusual species/habitat observation", category: "issue", required: false, status: "skipped" },
    ],
  },
  {
    id: "cl-mock-2",
    routeId: "SO-8-04-0",
    date: "2025-03-22",
    observer: "Marko P.",
    completionPercentage: 87,
    requiredComplete: true,
    items: [
      { id: "front", label: "Front view", category: "structure", required: true, status: "captured", visibility: "medium", photoPlaceholder: "DSC_0112_front.jpg", note: "Mild current, some particles in water" },
      { id: "back", label: "Back view", category: "structure", required: true, status: "captured", visibility: "medium", photoPlaceholder: "DSC_0113_back.jpg" },
      { id: "top", label: "Top / summit view", category: "structure", required: true, status: "captured", visibility: "medium", photoPlaceholder: "DSC_0114_top.jpg" },
      { id: "left", label: "Left side", category: "structure", required: false, status: "captured", visibility: "medium", photoPlaceholder: "DSC_0115_left.jpg" },
      { id: "right", label: "Right side", category: "structure", required: false, status: "skipped", note: "Current too strong on this side" },
      { id: "lower", label: "Lower side / shaded side", category: "structure", required: false, status: "captured", visibility: "poor", photoPlaceholder: "DSC_0116_lower.jpg", disturbanceRisk: "medium", note: "Dark, used torch briefly" },
      { id: "gp1", label: "Growth plate 1", category: "growth_plate", required: true, status: "captured", visibility: "good", photoPlaceholder: "DSC_0117_gp1.jpg", note: "Dense bryozoan mat forming" },
      { id: "gp2", label: "Growth plate 2", category: "growth_plate", required: true, status: "captured", visibility: "good", photoPlaceholder: "DSC_0118_gp2.jpg", note: "Mixed community: polychaetes + algae" },
      { id: "gp3", label: "Growth plate 3", category: "growth_plate", required: false, status: "captured", visibility: "good", photoPlaceholder: "DSC_0119_gp3.jpg" },
      { id: "gp4", label: "Growth plate 4", category: "growth_plate", required: false, status: "captured", visibility: "medium", photoPlaceholder: "DSC_0120_gp4.jpg" },
      { id: "gp5", label: "Growth plate 5", category: "growth_plate", required: false, status: "captured", visibility: "good", photoPlaceholder: "DSC_0121_gp5.jpg", note: "Mollusc attachment visible" },
      { id: "seabed", label: "Surrounding seabed", category: "context", required: false, status: "captured", visibility: "medium", photoPlaceholder: "DSC_0122_seabed.jpg" },
      { id: "wide", label: "Wide context shot", category: "context", required: false, status: "captured", visibility: "medium", photoPlaceholder: "DSC_0123_wide.jpg" },
      { id: "waste", label: "Any visible waste/damage", category: "issue", required: false, status: "skipped" },
      { id: "unusual", label: "Any unusual species/habitat observation", category: "issue", required: false, status: "skipped" },
    ],
  },
  {
    id: "cl-mock-3",
    routeId: "SO-8-06-1",
    date: "2025-04-05",
    observer: "Ana K.",
    completionPercentage: 93,
    requiredComplete: true,
    items: [
      { id: "front", label: "Front view", category: "structure", required: true, status: "captured", visibility: "good", photoPlaceholder: "IMG_2101_front_apr.jpg" },
      { id: "back", label: "Back view", category: "structure", required: true, status: "captured", visibility: "good", photoPlaceholder: "IMG_2102_back_apr.jpg" },
      { id: "top", label: "Top / summit view", category: "structure", required: true, status: "captured", visibility: "good", photoPlaceholder: "IMG_2103_top_apr.jpg", note: "More growth visible compared to March" },
      { id: "left", label: "Left side", category: "structure", required: false, status: "captured", visibility: "good", photoPlaceholder: "IMG_2104_left_apr.jpg" },
      { id: "right", label: "Right side", category: "structure", required: false, status: "captured", visibility: "good", photoPlaceholder: "IMG_2105_right_apr.jpg" },
      { id: "lower", label: "Lower side / shaded side", category: "structure", required: false, status: "captured", visibility: "medium", photoPlaceholder: "IMG_2106_lower_apr.jpg" },
      { id: "gp1", label: "Growth plate 1", category: "growth_plate", required: true, status: "captured", visibility: "good", photoPlaceholder: "IMG_2107_gp1_apr.jpg", note: "Increased coverage since March" },
      { id: "gp2", label: "Growth plate 2", category: "growth_plate", required: true, status: "captured", visibility: "good", photoPlaceholder: "IMG_2108_gp2_apr.jpg", note: "Possible seahorse near plate - kept distance" },
      { id: "gp3", label: "Growth plate 3", category: "growth_plate", required: false, status: "captured", visibility: "good", photoPlaceholder: "IMG_2109_gp3_apr.jpg" },
      { id: "gp4", label: "Growth plate 4", category: "growth_plate", required: false, status: "captured", visibility: "good", photoPlaceholder: "IMG_2110_gp4_apr.jpg" },
      { id: "gp5", label: "Growth plate 5", category: "growth_plate", required: false, status: "skipped", note: "Plate obscured by algae overgrowth" },
      { id: "seabed", label: "Surrounding seabed", category: "context", required: false, status: "captured", visibility: "good", photoPlaceholder: "IMG_2111_seabed_apr.jpg" },
      { id: "wide", label: "Wide context shot", category: "context", required: false, status: "captured", visibility: "good", photoPlaceholder: "IMG_2112_wide_apr.jpg" },
      { id: "waste", label: "Any visible waste/damage", category: "issue", required: false, status: "skipped" },
      { id: "unusual", label: "Any unusual species/habitat observation", category: "issue", required: false, status: "captured", visibility: "good", photoPlaceholder: "IMG_2113_seahorse_distance.jpg", note: "Possible seahorse approx 2m from gp2, photographed from distance" },
    ],
  },
  {
    id: "cl-mock-4",
    routeId: "SO-8-04-0",
    date: "2025-04-20",
    observer: "Marko P.",
    completionPercentage: 100,
    requiredComplete: true,
    items: [
      { id: "front", label: "Front view", category: "structure", required: true, status: "captured", visibility: "good", photoPlaceholder: "DSC_0201_front_apr20.jpg" },
      { id: "back", label: "Back view", category: "structure", required: true, status: "captured", visibility: "good", photoPlaceholder: "DSC_0202_back_apr20.jpg" },
      { id: "top", label: "Top / summit view", category: "structure", required: true, status: "captured", visibility: "good", photoPlaceholder: "DSC_0203_top_apr20.jpg", note: "Significant growth increase" },
      { id: "left", label: "Left side", category: "structure", required: false, status: "captured", visibility: "good", photoPlaceholder: "DSC_0204_left_apr20.jpg" },
      { id: "right", label: "Right side", category: "structure", required: false, status: "captured", visibility: "good", photoPlaceholder: "DSC_0205_right_apr20.jpg" },
      { id: "lower", label: "Lower side / shaded side", category: "structure", required: false, status: "captured", visibility: "medium", photoPlaceholder: "DSC_0206_lower_apr20.jpg" },
      { id: "gp1", label: "Growth plate 1", category: "growth_plate", required: true, status: "captured", visibility: "good", photoPlaceholder: "DSC_0207_gp1_apr20.jpg", note: "Dense coverage, multiple species" },
      { id: "gp2", label: "Growth plate 2", category: "growth_plate", required: true, status: "captured", visibility: "good", photoPlaceholder: "DSC_0208_gp2_apr20.jpg", note: "Polychaete dominance" },
      { id: "gp3", label: "Growth plate 3", category: "growth_plate", required: false, status: "captured", visibility: "good", photoPlaceholder: "DSC_0209_gp3_apr20.jpg" },
      { id: "gp4", label: "Growth plate 4", category: "growth_plate", required: false, status: "captured", visibility: "good", photoPlaceholder: "DSC_0210_gp4_apr20.jpg", note: "Still sparse, slower colonization" },
      { id: "gp5", label: "Growth plate 5", category: "growth_plate", required: false, status: "captured", visibility: "good", photoPlaceholder: "DSC_0211_gp5_apr20.jpg" },
      { id: "seabed", label: "Surrounding seabed", category: "context", required: false, status: "captured", visibility: "good", photoPlaceholder: "DSC_0212_seabed_apr20.jpg" },
      { id: "wide", label: "Wide context shot", category: "context", required: false, status: "captured", visibility: "good", photoPlaceholder: "DSC_0213_wide_apr20.jpg" },
      { id: "waste", label: "Any visible waste/damage", category: "issue", required: false, status: "skipped" },
      { id: "unusual", label: "Any unusual species/habitat observation", category: "issue", required: false, status: "skipped" },
    ],
  },
  {
    id: "cl-mock-5",
    routeId: "SO-8-06-1",
    date: "2025-05-03",
    observer: "Ana K.",
    completionPercentage: 80,
    requiredComplete: true,
    items: [
      { id: "front", label: "Front view", category: "structure", required: true, status: "captured", visibility: "good", photoPlaceholder: "IMG_2201_front_may.jpg" },
      { id: "back", label: "Back view", category: "structure", required: true, status: "captured", visibility: "good", photoPlaceholder: "IMG_2202_back_may.jpg" },
      { id: "top", label: "Top / summit view", category: "structure", required: true, status: "captured", visibility: "good", photoPlaceholder: "IMG_2203_top_may.jpg" },
      { id: "left", label: "Left side", category: "structure", required: false, status: "skipped" },
      { id: "right", label: "Right side", category: "structure", required: false, status: "skipped" },
      { id: "lower", label: "Lower side / shaded side", category: "structure", required: false, status: "captured", visibility: "medium", photoPlaceholder: "IMG_2204_lower_may.jpg" },
      { id: "gp1", label: "Growth plate 1", category: "growth_plate", required: true, status: "captured", visibility: "good", photoPlaceholder: "IMG_2205_gp1_may.jpg", note: "Continued growth, approaching dense" },
      { id: "gp2", label: "Growth plate 2", category: "growth_plate", required: true, status: "captured", visibility: "good", photoPlaceholder: "IMG_2206_gp2_may.jpg" },
      { id: "gp3", label: "Growth plate 3", category: "growth_plate", required: false, status: "captured", visibility: "good", photoPlaceholder: "IMG_2207_gp3_may.jpg" },
      { id: "gp4", label: "Growth plate 4", category: "growth_plate", required: false, status: "skipped" },
      { id: "gp5", label: "Growth plate 5", category: "growth_plate", required: false, status: "captured", visibility: "good", photoPlaceholder: "IMG_2208_gp5_may.jpg" },
      { id: "seabed", label: "Surrounding seabed", category: "context", required: false, status: "captured", visibility: "good", photoPlaceholder: "IMG_2209_seabed_may.jpg" },
      { id: "wide", label: "Wide context shot", category: "context", required: false, status: "captured", visibility: "good", photoPlaceholder: "IMG_2210_wide_may.jpg" },
      { id: "waste", label: "Any visible waste/damage", category: "issue", required: false, status: "skipped" },
      { id: "unusual", label: "Any unusual species/habitat observation", category: "issue", required: false, status: "captured", visibility: "good", photoPlaceholder: "IMG_2211_lobster_crevice.jpg", note: "Lobster spotted in crevice on west side" },
    ],
  },
];
