import { SEA_OASIS_LOCATION } from "./seaOasisConstants";
import type { DroneRoute3D, DroneWaypoint } from "./droneRouteTypes";

const WAYPOINTS: DroneWaypoint[] = [
  {
    id: "WP-00",
    label: "Surface marker above Sea Oasis",
    phase: "surface",
    localEastM: 0,
    localNorthM: 0,
    depthM: 0,
    yawDeg: 0,
    pitchDeg: -90,
    target: "surface-marker",
    captureRequired: false,
    dwellSeconds: 2,
    instruction: "Start at the surface above the Sea Oasis map location.",
  },
  {
    id: "WP-01",
    label: "Descent staging point",
    phase: "descent",
    localEastM: -4,
    localNorthM: -4,
    depthM: 6.4,
    yawDeg: 45,
    pitchDeg: -20,
    target: "wide-context",
    captureRequired: true,
    dwellSeconds: 4,
    instruction: "Descend to just above the structure summit depth. Capture a wide context shot.",
  },
  {
    id: "WP-02",
    label: "Front pass",
    phase: "certified-survey-loop",
    localEastM: 4,
    localNorthM: -4,
    depthM: 8.2,
    yawDeg: 315,
    pitchDeg: -10,
    target: "front-view",
    captureRequired: true,
    dwellSeconds: 5,
    instruction: "Move east along the front side. Capture the front face and nearby growth.",
  },
  {
    id: "WP-03",
    label: "Right side pass",
    phase: "certified-survey-loop",
    localEastM: 4,
    localNorthM: 4,
    depthM: 8.4,
    yawDeg: 225,
    pitchDeg: -10,
    target: "right-side",
    captureRequired: true,
    dwellSeconds: 5,
    instruction: "Move north along the right side. Capture side growth and visible organisms.",
  },
  {
    id: "WP-04",
    label: "Back lower pass",
    phase: "certified-survey-loop",
    localEastM: -4,
    localNorthM: 4,
    depthM: 9.8,
    yawDeg: 135,
    pitchDeg: -15,
    target: "back-view",
    captureRequired: true,
    dwellSeconds: 5,
    instruction: "Move west along the back side. Descend slightly for lower-side coverage.",
  },
  {
    id: "WP-05",
    label: "Left side return",
    phase: "certified-survey-loop",
    localEastM: -4,
    localNorthM: -4,
    depthM: 6.4,
    yawDeg: 45,
    pitchDeg: -15,
    target: "left-side",
    captureRequired: true,
    dwellSeconds: 5,
    instruction: "Move south along the left side and return to the loop start depth.",
  },
  {
    id: "WP-06",
    label: "Top and growth plate overview",
    phase: "growth-plate-inspection",
    localEastM: 0,
    localNorthM: 0,
    depthM: 6.3,
    yawDeg: 0,
    pitchDeg: -70,
    target: "top-summit",
    captureRequired: true,
    dwellSeconds: 6,
    instruction: "Move above the structure. Capture top/summit view and the five growth plate zones.",
  },
  {
    id: "WP-07",
    label: "Growth plate 1",
    phase: "growth-plate-inspection",
    localEastM: -1.8,
    localNorthM: -1.0,
    depthM: 7.4,
    yawDeg: 45,
    pitchDeg: -30,
    target: "growth-plate-1",
    captureRequired: true,
    dwellSeconds: 4,
    instruction: "Capture growth plate 1 from a stable distance.",
  },
  {
    id: "WP-08",
    label: "Growth plate 2",
    phase: "growth-plate-inspection",
    localEastM: 1.8,
    localNorthM: -1.0,
    depthM: 7.4,
    yawDeg: 315,
    pitchDeg: -30,
    target: "growth-plate-2",
    captureRequired: true,
    dwellSeconds: 4,
    instruction: "Capture growth plate 2 from a stable distance.",
  },
  {
    id: "WP-09",
    label: "Growth plate 3",
    phase: "growth-plate-inspection",
    localEastM: 1.8,
    localNorthM: 1.0,
    depthM: 7.8,
    yawDeg: 225,
    pitchDeg: -30,
    target: "growth-plate-3",
    captureRequired: true,
    dwellSeconds: 4,
    instruction: "Capture growth plate 3 from a stable distance.",
  },
  {
    id: "WP-10",
    label: "Growth plate 4",
    phase: "growth-plate-inspection",
    localEastM: -1.8,
    localNorthM: 1.0,
    depthM: 7.8,
    yawDeg: 135,
    pitchDeg: -30,
    target: "growth-plate-4",
    captureRequired: true,
    dwellSeconds: 4,
    instruction: "Capture growth plate 4 from a stable distance.",
  },
  {
    id: "WP-11",
    label: "Growth plate 5 / centre",
    phase: "growth-plate-inspection",
    localEastM: 0,
    localNorthM: 0,
    depthM: 8.0,
    yawDeg: 0,
    pitchDeg: -45,
    target: "growth-plate-5",
    captureRequired: true,
    dwellSeconds: 4,
    instruction: "Capture central growth plate / centre zone.",
  },
  {
    id: "WP-12",
    label: "Lower side and seabed scan",
    phase: "seabed-scan",
    localEastM: 0,
    localNorthM: -5.5,
    depthM: 10.2,
    yawDeg: 0,
    pitchDeg: -20,
    target: "waste-damage-scan",
    captureRequired: true,
    dwellSeconds: 6,
    instruction:
      "Scan surrounding seabed for waste, fishing line, sediment disturbance, or visible damage.",
  },
  {
    id: "WP-13",
    label: "Ascent point",
    phase: "ascent",
    localEastM: 0,
    localNorthM: 0,
    depthM: 0,
    yawDeg: 0,
    pitchDeg: 90,
    target: "surface-marker",
    captureRequired: false,
    dwellSeconds: 2,
    instruction: "Return to the surface marker. End of demo route.",
  },
];

export const SO_PIRAN_STANDARD_3D_DRONE_ROUTE: DroneRoute3D = {
  id: "SO-PIRAN-STANDARD-3D-DRONE",
  name: "Sea Oasis Piran standard 3D drone route",
  description:
    "Demo route based on public Sea Oasis dimensions and approximate local coordinate frame.",
  location: {
    latitude: SEA_OASIS_LOCATION.latitude,
    longitude: SEA_OASIS_LOCATION.longitude,
    dms: SEA_OASIS_LOCATION.dms,
  },
  structure: {
    lengthM: SEA_OASIS_LOCATION.structureLengthM,
    widthM: SEA_OASIS_LOCATION.structureWidthM,
    heightM: SEA_OASIS_LOCATION.structureHeightM,
    summitDepthM: SEA_OASIS_LOCATION.structureSummitDepthM,
    seabedDepthM: SEA_OASIS_LOCATION.modelSeabedDepthM,
    growthPlateCount: SEA_OASIS_LOCATION.growthPlateCount,
  },
  waypoints: WAYPOINTS,
  certifiedHorizontalSegment: {
    id: "SO-PIRAN-Z4-HORIZONTAL-LOOP",
    order: 4,
    exponents: [0, 1, 2, 3],
    directions: ["E", "N", "W", "S"],
    waypointIds: ["WP-01", "WP-02", "WP-03", "WP-04", "WP-05"],
    certificate: "\u03b6_4^0 + \u03b6_4^1 + \u03b6_4^2 + \u03b6_4^3 = 0",
    catalogType: "order-4 square loop",
    isMinimal: true,
  },
  verticalCertificate: "+1.8 + 0.2 + 1.4 - 3.4 = 0",
  isHorizontallyBalanced: true,
  isVerticallyBalanced: true,
  isDemoRoute: true,
};
