import { Observation } from "./schema";

export const MOCK_OBSERVATIONS: Observation[] = [
  {
    id: "mock-1", observer: "Ana K.", date: "2025-03-15", month: "2025-03",
    routeId: "SO-8-04-0", checklistId: "cl-mock-1",
    locationType: "artificial_reef", surveyMethod: "dive",
    visibility: "good", seaCondition: "calm", disturbanceLevel: "none",
    tags: [
      { tag: "fish", abundance: "many", confidence: "high", note: "Mixed school near NW corner" },
      { tag: "algae", abundance: "dominant", confidence: "high", note: "Green turf algae on all upper surfaces" },
      { tag: "bryozoans", abundance: "few", confidence: "medium", note: "Encrusting colonies on growth plates 1-2" },
    ],
    growthPlateScore: "2", wasteSeverity: "none", damageSeverity: "none",
    followUpNeeded: "none",
    notes: "First survey of season. Structure in good condition. Water temp approx 14C.",
    ethicsConfirmed: true, createdAt: "2025-03-15T10:00:00Z",
  },
  {
    id: "mock-2", observer: "Marko P.", date: "2025-03-22", month: "2025-03",
    routeId: "SO-8-04-0", checklistId: "cl-mock-2",
    locationType: "growth_plates", surveyMethod: "dive",
    visibility: "medium", seaCondition: "mild_current", disturbanceLevel: "low",
    tags: [
      { tag: "polychaetes", abundance: "few", confidence: "medium", note: "Fan worms on plate 2, tube worms on plate 1" },
      { tag: "artificial_reef_growth", abundance: "many", confidence: "high", note: "Plates 1-3 showing good colonization" },
      { tag: "molluscs", abundance: "few", confidence: "high", note: "Small bivalves attached to plate edges" },
    ],
    growthPlateScore: "3", wasteSeverity: "none", damageSeverity: "none",
    followUpNeeded: "none",
    notes: "Growth plates progressing well. Plate 4 still lagging - possibly too exposed to current.",
    ethicsConfirmed: true, createdAt: "2025-03-22T09:30:00Z",
  },
  {
    id: "mock-3", observer: "Ana K.", date: "2025-04-05", month: "2025-04",
    routeId: "SO-8-06-1", checklistId: "cl-mock-3",
    locationType: "artificial_reef", surveyMethod: "dive",
    visibility: "good", seaCondition: "calm", disturbanceLevel: "none",
    tags: [
      { tag: "fish", abundance: "many", confidence: "high", note: "Larger school than March, some juveniles" },
      { tag: "seahorse", abundance: "one", confidence: "low", note: "Possible sighting near growth plate 2, approx 15cm, brown/grey. Kept 2m distance. Photo IMG_2113" },
      { tag: "algae", abundance: "dominant", confidence: "high" },
      { tag: "juvenile_fish", abundance: "few", confidence: "medium", note: "3-4 small individuals sheltering in structure gaps" },
    ],
    growthPlateScore: "2", wasteSeverity: "none", damageSeverity: "none",
    followUpNeeded: "expert_review",
    notes: "Possible seahorse sighting needs expert confirmation from photo. Did not approach closer than 2m. Overall reef condition improving month over month.",
    ethicsConfirmed: true, createdAt: "2025-04-05T11:00:00Z",
  },
  {
    id: "mock-4", observer: "Petra L.", date: "2025-04-12", month: "2025-04",
    locationType: "coastline", surveyMethod: "snorkel",
    visibility: "medium", seaCondition: "mild_current", disturbanceLevel: "low",
    tags: [
      { tag: "waste", abundance: "few", confidence: "high", note: "2 plastic bottles, 1 food wrapper near rocky outcrop" },
      { tag: "plastic", abundance: "few", confidence: "high", note: "Degraded plastic fragments on seabed" },
      { tag: "fishing_line", abundance: "one", confidence: "high", note: "Approx 3m monofilament tangled on rock, did not remove (entangled with organisms)" },
    ],
    wasteSeverity: "medium", damageSeverity: "low",
    followUpNeeded: "cleanup_needed",
    notes: "Fishing line tangled on rocky outcrop at NE boundary. Not safe to remove while snorkeling - needs diver with cutting tool. Plastic items not entangled, could be collected on next dive.",
    ethicsConfirmed: true, createdAt: "2025-04-12T14:00:00Z",
  },
  {
    id: "mock-5", observer: "Marko P.", date: "2025-04-20", month: "2025-04",
    routeId: "SO-8-04-0", checklistId: "cl-mock-4",
    locationType: "growth_plates", surveyMethod: "dive",
    visibility: "good", seaCondition: "calm", disturbanceLevel: "none",
    tags: [
      { tag: "bryozoans", abundance: "many", confidence: "high", note: "Thick encrusting mat on plates 1, 2, 3" },
      { tag: "polychaetes", abundance: "many", confidence: "high", note: "Tube density increasing, fan worms more numerous" },
      { tag: "artificial_reef_growth", abundance: "dominant", confidence: "high", note: "Plates 1-3 approaching full coverage" },
    ],
    growthPlateScore: "3", wasteSeverity: "none", damageSeverity: "none",
    followUpNeeded: "none",
    notes: "Clear improvement in colonization since March. Plate 4 finally showing initial settlement. Recommend comparing photos DSC_0207-0211 with March shots for presentation.",
    ethicsConfirmed: true, createdAt: "2025-04-20T10:00:00Z",
  },
  {
    id: "mock-6", observer: "Ana K.", date: "2025-05-03", month: "2025-05",
    routeId: "SO-8-06-1", checklistId: "cl-mock-5",
    locationType: "artificial_reef", surveyMethod: "dive",
    visibility: "good", seaCondition: "calm", disturbanceLevel: "none",
    tags: [
      { tag: "fish", abundance: "dominant", confidence: "high", note: "Large mixed school, estimated 40+ individuals" },
      { tag: "algae", abundance: "many", confidence: "high", note: "Reduced from dominant - grazing pressure from fish?" },
      { tag: "seagrass", abundance: "few", confidence: "medium", note: "Small posidonia patch establishing 2m south of structure" },
      { tag: "lobster", abundance: "one", confidence: "medium", note: "In crevice on west side, approx 20cm, photo IMG_2211 from 1.5m" },
    ],
    growthPlateScore: "2", wasteSeverity: "none", damageSeverity: "none",
    followUpNeeded: "none",
    notes: "Reef maturing nicely. Fish population clearly increasing. Lobster presence is a positive indicator. Posidonia colonization near base is exciting - natural expansion from nearby meadow.",
    ethicsConfirmed: true, createdAt: "2025-05-03T09:00:00Z",
  },
  {
    id: "mock-7", observer: "Petra L.", date: "2025-05-10", month: "2025-05",
    locationType: "seagrass_meadow", surveyMethod: "snorkel",
    visibility: "medium", seaCondition: "mild_current", disturbanceLevel: "low",
    tags: [
      { tag: "seagrass", abundance: "dominant", confidence: "high", note: "Dense posidonia meadow, blade length 30-40cm" },
      { tag: "fish", abundance: "many", confidence: "high", note: "Wrasse and damselfish common in meadow" },
      { tag: "crab", abundance: "few", confidence: "medium", note: "2 spider crabs observed on seagrass blades" },
    ],
    growthPlateScore: "unknown", wasteSeverity: "low", damageSeverity: "none",
    followUpNeeded: "none",
    notes: "Meadow in good condition. One small plastic fragment collected (not entangled). Blade density appears healthy. Epiphyte load moderate.",
    ethicsConfirmed: true, createdAt: "2025-05-10T15:00:00Z",
  },
  {
    id: "mock-8", observer: "Marko P.", date: "2025-05-18", month: "2025-05",
    routeId: "SO-8-04-0",
    locationType: "artificial_reef", surveyMethod: "dive",
    visibility: "good", seaCondition: "calm", disturbanceLevel: "none",
    tags: [
      { tag: "fish", abundance: "dominant", confidence: "high" },
      { tag: "bryozoans", abundance: "many", confidence: "high" },
      { tag: "polychaetes", abundance: "many", confidence: "high" },
      { tag: "eggs_larvae", abundance: "few", confidence: "low", note: "Small egg mass observed on plate 3, species unknown" },
      { tag: "unknown_organism", abundance: "one", confidence: "low", note: "Gelatinous organism on plate 5, approx 3cm diameter, translucent" },
    ],
    growthPlateScore: "3", wasteSeverity: "none", damageSeverity: "none",
    followUpNeeded: "expert_review",
    notes: "Unknown gelatinous organism on growth plate 5 - possibly tunicate or bryozoan colony. Egg mass on plate 3 needs ID. Photos forwarded for expert review.",
    ethicsConfirmed: true, createdAt: "2025-05-18T10:30:00Z",
  },
];
